name: ci

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install depends
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run application
        run: python app.py &
      
